### ISSUE TITLE
Local SGD does not match the paper description

### ISSUE THREAD

**Issue by QiTianyu-0403** [LuminLiu/HierFL#4]
First thanks to the author for the open source code. The current training results are correct. But I think there are some parts of the code that are different from the paper description. The problem is embodied in the `local_update` function in the `client.py` file:
```
itered_num = 0
loss = 0.0
end = False
# the upperbound selected in the following is because it is expected that one local update will never reach 1000
for epoch in range(1000):
    for data in self.train_loader:
        inputs, labels = data
        inputs = Variable(inputs).to(device)
        labels = Variable(labels).to(device)
        loss += self.model.optimize_model(input_batch=inputs,
                                                     label_batch=labels)
        itered_num += 1
        if itered_num >= num_iter:
            end = True
            # print(f"Iterer number {itered_num}")
            self.epoch += 1
            self.model.exp_lr_sheduler(epoch=self.epoch)
            # self.model.print_current_lr()
            break
    if end: break
    self.epoch += 1
    self.model.exp_lr_sheduler(epoch = self.epoch)
loss /= num_iter
```
tau_1 in the paper should be `num_iter` here,  that is, the number of epochs of the local SGD. But what should be implemented in the code should be the number of batches. While the results are good, this should contradict the paper. Looking forward to your answer, thanks.

**Comment by LuminLiu** [comment]
Hi, \tau_1 is the number of sgd iterations, so it is equal to the number of batches.
