### ISSUE TITLE
HierFAVG with CIFAR-10

### ISSUE THREAD

**Issue by nsmalotaibi** [LuminLiu/HierFL#5]
Hi Liu,
First of all, thank you for sharing the valuable work with community.

I tried to run the HierFAVG with CIFAR10 with the remaining models but unfortunately it shows some error.
Can you provide us with the remaining files if any or guide me please??

Noura

**Comment by nsmalotaibi** [comment]
Please Mr. Liu can you reply and consider my issue?
I am looking forward to run the full project as in your paper ..

Thanks

**Comment by LuminLiu** [comment]
Hi, can you post your error message so I can help you better?

**Comment by LuminLiu** [comment]
Hi, can you post more details about the error message?

**Comment by nsmalotaibi** [comment]
Hi, First of all, thanks for your reply ..
Actually, most of the functions gave me errors when working with Cifar10 dataset e.g. niid_esize_split, niid_esize_split_oneclass.. (cifar10 does not have test_labels) which unfortunately, preventing me from replicating your algorithm on cifar10 and other datasets. I checked Google and I know there are no train_labels and test-labels any more on Cifar10 but it was core distinguish in your splitting method. 
Also, cifar10 CCN models gave me errors regarding the **average weights** as shown here. 
<img width="451" alt="image" src="https://user-images.githubusercontent.com/123098533/230280823-60d02ef9-dc7c-4890-ab2b-dce0a8fd82a4.png">
I tried for several days but with no luck .. and I am looking forward to hearing from you. 
thanks again

**Comment by LuminLiu** [comment]
Hi, here is some advice for the problems you met:
1. cifar10 does not have test_labels: this is due to the package update of torchvision. In recent versions, the variable for the labels for the training samples in torchvision.datasets.CIFAR10 is not called "test_labels" anymore, instead, it is called "targets". Consequently, you have to change the "test_labels" variable for "targets".
2. "result type cannot be output to the desired output type long": this is also due to the update of the torch package. Please try to downgrade your torch package or your can manually change the data type.

**Comment by jiayoudaima** [comment]
Hi Mr. Liu, first of all thank you for sharing the source code.
 I can't reproduce the results of your experiment. When the number of communication rounds with the cloud is constant, no matter how I adjust the values of k1 and k2, the accuracy is very close, but in your experiment, the values of k1 and k2 are different, and the accuracy is very different. 
This issue has been bothering me for a month, I tried various methods to improve it, the effect is not very obvious, eager to get a response from you.

**Comment by jiayoudaima** [comment]
Hi ，Mr. Liu, first of all thank you for sharing the source code.
I can't reproduce the results of your experiment. When the number of communication rounds with the cloud is constant, no matter how I adjust the values of k1 and k2, the accuracy is very close, but in your experiment, the values of k1 and k2 are different, and the accuracy is very different.
This issue has been bothering me for a month, I tried various methods to improve it, the effect is not very obvious, eager to get a response from you.

**Comment by jiayoudaima** [comment]
Hi ，Mr. Liu, 
First of all thank you for sharing the source code.
I can't reproduce the results of your experiment. When the number of communication rounds with the cloud is constant, no matter how I adjust the values of k1 and k2, the accuracy is very close, but in your experiment, the values of k1 and k2 are different, and the accuracy is very different.
This issue has been bothering me for a month, I tried various methods to improve it, the effect is not very obvious, eager to get a response from you.

**Comment by nsmalotaibi** [comment]
> 

Hello Mr. Liu,
Thanks again for your reply.. 
1- You are right. I found that the train_labels have been changed to targets and I already tried your suggestion but it impacted the result very seriously (it gave an accuracy of 0.1081) I guess because the code distinguishes between train_labels and test_labels (    # is_shuffle is used to differentiate between train and test
    if is_shuffle:
        labels = dataset.train_labels
    else:
        labels = dataset.test_labels ) 
But with the new version, the train_labels became targets and if I place test_labels also with targets, so if else statement it is not valid any more??

2- The issue appears on Cifar10 and not with MNIST..
Can you consider any improvement that can make your amazing work be standardized? 

Many thanks again for your amazing work!

**Comment by LuminLiu** [comment]
Hi, thanks for your proposal for standardisation, I will consider to update the code in the future, if I have time😊.

For your first problem, the reason might be that with niid_esize_split_oneclass data split on CIFAR-10, the training performance is actually that bad. You might try to reduce the value of k1 and k2 to see if you can get better results.
