### ISSUE TITLE
Experimental results

### ISSUE THREAD

**Issue by Sillage-shuo** [LuminLiu/HierFL#8]
Hi liu,
Thank you very much for opening the source code, but I have some queries to ask you. 
I am using the parameters:python3 hierfavg.py --dataset mnist --model lenet --num_clients 50 --num_edges 5 --frac 1 --num_local_update 60 --num_edge_aggregation 10 - --num_communication 200 ---batch_size 20 --iid -2 --edgeiid 1 --show_dis 1 --lr 0.01 --lr_decay 0.995 --lr_decay_epoch 1 --momentum 0 --weight_decay 0. 
When fixing k1k2=60 and using the values from the paper for setting k1 and k2, the conclusions are similar to those in the paper, but not as correct as in the paper. 
What I would like to know most is that when setting the value of k1(--num_local_update) to 60, changing k2(--num_edge_aggregation) changes the training effect to a great extent, which is different from the experimental results and conclusions in the paper. Can you please answer my query? Thanks.

**Comment by LuminLiu** [comment]
Hi can you explain more about the experimental results and the conclusions that are different?

**Comment by Sillage-shuo** [comment]
The most obvious is this part:
<img width="692" alt="Snipaste_2023-11-11_14-08-53" src="https://github.com/LuminLiu/HierFL/assets/79360271/de79e82f-4cd4-4b60-b9b1-3590564fe8b7">
The parameters are set as follows:python3 hierfavg.py --dataset mnist --model lenet --num_clients 50 --num_edges 5 --frac 1 --num_local_update 60 --num_edge_aggregation 4 --num_communication 200 --batch_size 20 --iid -2 --edgeiid 1 --show_dis 1 --lr 0.01 --lr_decay 0.995 --lr_decay_epoch 1 --momentum 0 --weight_decay 0.
In the Edge-IID case, the difference between the two runs is --num_edge_aggregation, which is 1 and 4. The difference in accuracy between the two runs is quite large. But the paper changes -num_edge_aggregation seems to be about the same. Why is that? Is there something wrong with my understanding or the code does not run correctly? I look forward to your reply.

**Comment by LuminLiu** [comment]
I think the main reason is that the x-axis is every communication round with the cloud server. Thus, for the setting t1-60_t2-4, every communication round with the cloud equals to t1*t2 = 240 steps of local update. While the setting t1-60_t2-1 equals to 60. If you want a fair comparison in terms of convergence speed, you need to pay attention to this.

**Comment by Sillage-shuo** [comment]
Thank you for your answer. I have learned that I misunderstood the meaning of the X-axis in the figure of the paper. Thank you again for your answer.
